name: ci

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read


    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      - name: Run typecheck
        run: npm run typecheck

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        version: [20, 22, 24, 25]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --coverage

      - name: 'Report Coverage'
        if: always()
        uses:  davelosert/vitest-coverage-report-action@v2
